# This code is part of Tergite
#
# (C) Copyright Chalmers Next Labs 2024
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

[build-system]
requires = ["setuptools>=61.0", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "tergite-tuner"
version = "2026.06.0-rc.2"
description = "Library to tune up the WACQT quantum computers"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
authors = [
    { name = "Eleftherios Moschandreou", email = "elemos@chalmers.se" },
    { name = "Liangyu Chen", email = "liangyuc@chalmers.se" },
    { name = "Stefan Hill", email = "stefanhi@chalmers.se" },
    { name = "Amr Osman", email = "oarm@chalmers.se" },
    { name = "Tong Liu", email = "liuto@chalmers.se" },
    { name = "Joel Sandås", email = "sandas@chalmers.se" },
    { name = "Pontus Vikstål", email = "pontus.vikstal@chalmersnextlabs.se" },
    { name = "Michele Faucci Giannelli", email = "faucci@chalmers.se" },
    { name = "Axel Erik Andersson", email = "axean@chalmers.se" },
    { name = "Martin Ahindura", email = "ahindura@chalmers.se"},
    { name = "Adilet Tuleuov", email = "adilet@chalmers.se"},
]
maintainers = [
    { name = "Chalmers Next Labs AB", email = "contact@quantum.chalmersnextlabs.se" }
]
requires-python = ">=3.12, <3.13"
dependencies = [
    "h5py>=3.12.1",
    "numpy>=2.0",
    "qblox-instruments~=0.14.2",
    "qcodes~=0.49.0",
    "quantify-scheduler~=0.22.2",
    "redis>=5.0.0",
    "scikit-learn~=1.5.2",
    "toml>=0.10.2",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "netcdf4~=1.7.1.post2",
    "tomlkit>=0.13.2",
    "matplotlib>=3.9.3",
    "scipy>=1.14.1",
    "pandas>=2.2.3",
    "xarray>=2024.11.0",
    "pydantic~=2.11.3",
    "networkx~=3.4.2",
]

[dependency-groups]
dev = [
    "black>=24.10.0",
    "isort>=5.12.0",
    "pylint>=3.3.8"
]
test = [
    "pytest>=8.3.3",
    "requests-mock>=1.11.0",
    "pytest-cov>=7.0.0",
    "fakeredis[lua]>=2.32.1"
]

[project.urls]
Homepage = "https://github.com/tergite/tergite-tuner"
Repository = "https://github.com/tergite/tergite-tuner"
Documentation = "https://github.com/tergite/tergite-tuner"
Issues = "https://github.com/tergite/tergite-tuner/issues"
Changelog = "https://github.com/tergite/tergite-tuner/blob/main/CHANGELOG.md"

[tool.setuptools.packages.find]
include = ["tergite_tuner*"]
exclude = ["*.tests", "*.tests.*", "examples*", "*.data", "*.data.*"]

[tool.isort]
skip_gitignore = true