
# FIXME: Update the graph dependencies
GRAPH_DEPENDENCIES = [
    ("tof", "resonator_spectroscopy"),
    ("resonator_spectroscopy", "resonator_spectroscopy_vs_current"),
    ("qubit_01_spectroscopy", "coupler_anticrossing"),
    ("resonator_spectroscopy", "qubit_bring_up_spectroscopy"),
    ("resonator_spectroscopy", "qubit_01_spectroscopy"),
    ("resonator_spectroscopy_vs_current", "qubit_spectroscopy_vs_current"),
    ("qubit_01_spectroscopy", "rabi_oscillations"),
    ("rabi_oscillations", "ramsey_correction"),
    ("ramsey_correction", "T1"),
    ("ramsey_correction", "motzoi_parameter"),
    ("motzoi_parameter", "n_rabi_oscillations"),
    ("n_rabi_oscillations", "resonator_spectroscopy_1"),
    ("resonator_spectroscopy_1", "ro_frequency_two_state_optimization"),
    ("ro_frequency_two_state_optimization", "ro_amplitude_two_state_optimization"),
    ("n_rabi_oscillations", "all_XY"),
    ("resonator_spectroscopy_1", "qubit_12_spectroscopy"),
    ("qubit_12_spectroscopy", "rabi_oscillations_12"),
    ("rabi_oscillations_12", "ramsey_correction_12"),
    ("ramsey_correction_12", "motzoi_12_parameter"),
    ("motzoi_12_parameter", "n_rabi_12_oscillations"),
    ("motzoi_12_parameter", "resonator_spectroscopy_2"),
    # ("n_rabi_12_oscillations", "resonator_spectroscopy_2"),
    ("resonator_spectroscopy_2", "ro_frequency_three_state_optimization"),
    ("ro_frequency_three_state_optimization", "ro_amplitude_three_state_optimization"),
    ("ro_frequency_three_state_optimization", "three_state_discrimination"),
    ("ro_amplitude_three_state_optimization", "cz_parametrization"),
    ("T1", "T2"),
    ("T2", "T2_echo"),
    ("ro_amplitude_three_state_optimization", "randomized_benchmarking"),
    ("T2_echo", "purity_benchmarking"),
    ("cz_parametrization", "cz_chevron"),
    ("cz_chevron", "cz_calibration"),
    ("cz_calibration", "cz_local_phases"),
    ("cz_local_phases", "cz_rb"),
    ("ro_amplitude_three_state_optimization", "process_tomography_ssro"),
]
